### ISSUE TITLE
importRegExp doesn't support ES6-style & named imports

### ISSUE THREAD

**Issue by samuelgoff** [vanruesc/inline-import#1]
@vanruesc thanks so much for creating `inline-import`! 🙏🏼 I'm looking to inline multiple ES6 named imports into a single file, & I'm encountering a couple of issues:
- The `importRegExp` at https://github.com/vanruesc/inline-import/blob/285a6a2059af483b7bda25c9d451bdab0df8f8e4/src/core/InlineImport.js#L15 only handles certain import types, n which excludes a lot of different formats that are perfectly valid in ES6, including named imports. For example, here is a [regex](regexr.com/47jlq) that demonstrates all of the ES6 formats that are able to be supported, whereas here is the above [`importRegExp`](regexr.com/6q968) tested against the same formats.
- Multiple named imports per `import` statement are not supported
- ES6 allows (and linting rules enforce) you to omit the file extension from the `import` statement. It would be great if you could omit file format extension & this would still work.

**Comment by vanruesc** [comment]
I originally created this project to inline shader files in JS modules when bundlers were still pretty new. Now there are better, non-destructive ways to import special files via bundler plugins.

I'm not actively maintaining this project anymore, but PRs are welcome!

**Comment by samuelgoff** [comment]
> Now there are better, non-destructive ways to import special files via bundler plugins.

Hey @vanruesc what plug-ins? I’ve been looking, but I haven’t found anything that does the trick. Perhaps I’m not using the right keywords or terminology.

**Comment by vanruesc** [comment]
It depends on the bundler; if you use [esbuild](https://esbuild.github.io/) for example, you can use one of the plugins listed [here](https://github.com/esbuild/community-plugins#new-file-extensions-hosted-on-npm). Or if you use [rollup](https://rollupjs.org/guide/en/), you can use one of [these](https://github.com/rollup/awesome#other-file-imports).

**Comment by samuelgoff** [comment]
Hey @vanruesc thanks so much for pointing me in the right direction! Once I started using the term "bundler" in my search, everything fell into place. 🙏🏼
